trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
# =======================
# 1️⃣ Build Stage
# =======================
- stage: Build
  displayName: "Build HTML Website"
  jobs:
  - job: BuildJob
    displayName: "Validate and Package Website"
    steps:
    - checkout: self

    - script: |
        echo "🔍 Validating HTML files..."
        ls -R website
      displayName: "List Website Files"

    - script: |
        echo "📦 Packaging website into a zip file..."
        zip -r website.zip website/
      displayName: "Zip Website Folder"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'website.zip'
        ArtifactName: 'html_website'
        publishLocation: 'Container'
      displayName: "Publish Website Artifact"


# =======================
# 2️⃣ Deploy Stage
# =======================
- stage: Deploy
  displayName: "Deploy HTML Website"
  dependsOn: Build
  jobs:
  - deployment: DeployJob
    displayName: "Deploy to Web Server"
    environment: "production"
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: html_website
            displayName: "Download Website Artifact"

          - script: |
              echo "🚀 Deploying website..."
              mkdir -p /var/www/html/
              unzip -o $(Pipeline.Workspace)/html_website/website.zip -d /var/www/html/
              echo "✅ Deployment completed!"
            displayName: "Copy Website Files to Web Root"
